# -*- coding: utf-8 -*-
"""INSURANCE_APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-lHfQWkuZ-Gj3M6C-Gz-qpFaD7HRdlV
"""

import streamlit as st
import numpy as np
import pickle
from gtts import gTTS
import uuid
import os
import streamlit.components.v1 as components

# -------------------- Set Page Config --------------------
st.set_page_config(page_title="💼 Insurance Predictor", layout="centered", page_icon="💰")

# -------------------- Load Model --------------------
@st.cache_resource
def load_model():
    with open('insurance_model.pkl', 'rb') as f:
        return pickle.load(f)

model = load_model()

# -------------------- Banner & UI --------------------
st.markdown("""
    <style>
        .banner {
            background-color: #D1ECF1;
            color: #0C5460;
            padding: 10px;
            border-radius: 10px;
            text-align: center;
            animation: moveBanner 15s linear infinite;
        }
        @keyframes moveBanner {
            0% {transform: translateX(-100%);}
            50% {transform: translateX(0);}
            100% {transform: translateX(100%);}
        }
        .title {
            font-size: 48px;
            color: #4B8BBE;
            text-align: center;
        }
        .subtitle {
            font-size: 18px;
            color: #666;
            text-align: center;
        }
    </style>
    <div class="title">💰 Insurance Charges Estimator</div>
    <div class="subtitle">Accurate predictions using AI - Powered by Linear Regression</div>
    <div class="banner">🏥 Predict Medical Charges Instantly | Streamlit Pro UI 🌟</div>
""", unsafe_allow_html=True)

# -------------------- Input Form --------------------
with st.form("prediction_form", clear_on_submit=False):
    st.subheader("🧾 Enter Personal Information")

    col1, col2 = st.columns(2)

    with col1:
        age = st.slider("🎂 Age", 18, 100, 30)
        bmi = st.number_input("⚖️ BMI", min_value=10.0, max_value=50.0, value=25.0)
        children = st.number_input("👶 Number of Children", min_value=0, max_value=10, step=1)

    with col2:
        sex = st.radio("🧑 Sex", ['Male', 'Female'], horizontal=True)
        smoker = st.radio("🚬 Smoker", ['Yes', 'No'], horizontal=True)

    sex_encoded = 1 if sex == "Male" else 0
    smoker_encoded = 1 if smoker == "Yes" else 0

    submit = st.form_submit_button("🔍 Estimate Charges")

# -------------------- Prediction & Audio --------------------
if submit:
    data = np.array([[age, sex_encoded, bmi, children, smoker_encoded]])
    prediction = model.predict(data)[0]
    cost = f"${prediction:,.2f}"
    st.success(f"💵 Estimated Charges: **{cost}**")

    # Speak the cost using gTTS
    prediction_text = f"Your estimated medical charges are {cost.replace('$', '').replace(',', '')} dollars"
    tts = gTTS(prediction_text)
    filename = f"audio_{uuid.uuid4().hex}.mp3"
    tts.save(filename)

    # Play the audio automatically
    audio_html = f"""
        <audio autoplay>
            <source src="{filename}" type="audio/mp3">
            Your browser does not support the audio element.
        </audio>
    """
    components.html(audio_html, height=0)

# -------------------- Footer --------------------
st.markdown("---")
st.markdown("""
    <div style='text-align: center; color: grey; font-size: 13px;'>
        Created with ❤️ by <strong>konjam_kadhalxx</strong> | Using Streamlit, Python & Machine Learning
    </div>
""", unsafe_allow_html=True)
